// HEADER
export const SET_HEADER_LINKS = "SET_HEADER_LINK";
export const SET_NAVBAR_LINKS = "SET_NAVBAR_LINK";
export const CHANGE_NAVBAR_ACTIVE = "CHANGE_NAVBAR_ACTIVE";

// USER
export const SET_USER_PURCHASES = "SET_USER_PURCHASES";